# Generated by Django 3.2.5 on 2021-07-26 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('workmail', models.EmailField(max_length=254, unique=True)),
                ('position', models.CharField(choices=[('D', 'Director'), ('M', 'Manager'), ('CCO', 'CCOperator'), ('C', 'Cleaner')], default=None, max_length=100)),
            ],
            options={
                'verbose_name': 'Сотрудник компании',
                'verbose_name_plural': 'Сотрудники компании',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('title', models.CharField(choices=[('APL1', 'Заявка на ремонт'), ('APL2', 'Заявка на звонок'), ('APL3', 'Заявка на выезд курьера'), ('APL4', 'Заявка на подау документов'), ('APL5', 'ЗАявка на получение документов'), ('APL6', 'Заявка для устрава на работу')], max_length=100)),
                ('number', models.CharField(help_text='Пример 9134567891', max_length=10, unique=True, verbose_name='Номер телефона')),
                ('mail', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Электронная почта')),
                ('tel_name', models.CharField(default=None, help_text='Без @', max_length=4000, unique=True, verbose_name='Имя пользователя в ТГ')),
                ('notifications', models.BooleanField(default=False)),
                ('profile_id', models.IntegerField(blank=True, null=True, verbose_name='ID чата')),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('inwork', 'В работе'), ('closed', 'Закрыта')], max_length=100, null=True)),
                ('createdate', models.DateTimeField(auto_now=True)),
                ('membercall', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='coreapp.membermodel')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
