# Generated by Django 3.2.5 on 2021-07-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='status',
            field=models.CharField(choices=[('open', 'Открыта'), ('inwork', 'В работе'), ('closed', 'Закрыта')], default='open', max_length=100),
        ),
    ]
