# Generated by Django 3.2.5 on 2021-07-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_alter_usermodel_membercall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='status',
            field=models.CharField(choices=[('open', 'Открыта'), ('inwork', 'В работе'), ('closed', 'Закрыта')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='title',
            field=models.CharField(choices=[('Заявка на ремонт', 'Заявка на ремонт'), ('Заявка на звонок', 'Заявка на звонок'), ('Заявка на выезд курьера', 'Заявка на выезд курьера'), ('Заявка на подау документов', 'Заявка на подау документов'), ('Заявка на получение документов', 'Заявка на получение документов'), ('Заявка для устрава на работу', 'Заявка для устрава на работу')], max_length=100),
        ),
    ]
